import Foundation

// MARK: - Effect parameter model

public enum KParamType: String, Codable, Sendable {
    case float
    case int
    case color
    case bool
    case select
}

public struct ParamSpec: Hashable, Codable, Sendable {
    public var key: String
    public var name: String
    public var type: KParamType
    public var min: Float
    public var max: Float
    public var defaultValue: Float
    public var step: Float
    /// select options for type == .select (index range maps to options).
    public var options: [String]

    public init(key: String, name: String, type: KParamType, min: Float = 0, max: Float = 1,
                defaultValue: Float = 0, step: Float = 0.01, options: [String] = []) {
        self.key = key
        self.name = name
        self.type = type
        self.min = min
        self.max = max
        self.defaultValue = defaultValue
        self.step = step
        self.options = options
    }
}

/// Kinds of renderer implementations.
public enum KEffectImpl: String, Codable, Sendable {
    /// Core Image chain generated by the platform layer (CI*).
    case coreImage
    /// Custom Metal kernel (defined in app's shader library; requires high-priority usage).
    case metal
    /// Parameter-only tweaks (e.g. brightness knob reused across effects).
    case colorAdjust
    /// Interactive region (e.g. lens flare position) with animated overlays.
    case compositor
}

/// Declaration of an available effect (catalogue entry).
public struct EffectSpec: Hashable, Codable, Sendable {
    public var id: String
    public var name: String
    public var family: String
    public var impl: KEffectImpl
    public var params: [ParamSpec]
    /// True when the effect supports per-time animation (keyframes baked in store).
    public var animatable: Bool

    public init(id: String, name: String, family: String, impl: KEffectImpl, params: [ParamSpec], animatable: Bool = true) {
        self.id = id
        self.name = name
        self.family = family
        self.impl = impl
        self.params = params
        self.animatable = animatable
    }

    public func param(_ key: String) -> ParamSpec? { params.first { $0.key == key } }
}

/// A concrete instance of an effect with explicit parameter values.
public struct EffectInstance: Hashable, Codable, Sendable {
    public var specID: String
    /// Ordered key → value; unspecified keys fall back to defaults at render time.
    public var values: [String: Float]
    /// Strength scalar (0..1) multiplied over the whole effect.
    public var strength: Float

    public init(specID: String, values: [String: Float] = [:], strength: Float = 1) {
        self.specID = specID
        self.values = values
        self.strength = strength
    }

    public func value(_ key: String, spec: EffectSpec?) -> Float {
        if let v = values[key] { return v }
        return spec?.param(key)?.defaultValue ?? 0
    }

    // MARK: Preset catalogue — original Kino effect library.

    /// Built-in library. Each entry is declared with a family; the iOS renderer
    /// maps family+id to Core Image/Metal implementations.
    public static let catalogue: [EffectSpec] = {
        func spec(_ id: String, _ name: String, _ family: String, _ impl: KEffectImpl, _ params: [ParamSpec], _ an: Bool = true) -> EffectSpec {
            EffectSpec(id: "kino.\(id)", name: name, family: family, impl: impl, params: params, animatable: an)
        }
        let f = ParamSpec(key: "amount", name: "Amount", type: .float, min: 0, max: 1, defaultValue: 1, step: 0.01)
        let gentle = ParamSpec(key: "radius", name: "Radius", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.01)
        return [
            // Blur family
            spec("blur.gaussian", "Gaussian Blur", "Blur", .coreImage, [f, gentle]),
            spec("blur.radial", "Radial Blur", "Blur", .coreImage, [f, gentle]),
            spec("blur.motion", "Motion Blur", "Blur", .coreImage, [f, gentle, ParamSpec(key: "angle", name: "Angle", type: .float, min: -180, max: 180, defaultValue: 0, step: 1)]),
            spec("blur.focus", "Focus Pull", "Blur", .coreImage, [f, gentle, ParamSpec(key: "angle", name: "Angle", type: .float, min: -180, max: 180, defaultValue: 0, step: 1)]),
            // Light & lens
            spec("light.flare", "Lens Flare", "Light", .metal, [f, ParamSpec(key: "x", name: "X", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.01), ParamSpec(key: "y", name: "Y", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.01), ParamSpec(key: "color", name: "Color", type: .color, min: 0, max: 1, defaultValue: 0, step: 1)]),
            spec("light.leak", "Light Leak", "Light", .coreImage, [f, ParamSpec(key: "hue", name: "Hue", type: .float, min: 0, max: 1, defaultValue: 0.7, step: 0.01)]),
            spec("light.glow", "Glow", "Light", .coreImage, [f, ParamSpec(key: "threshold", name: "Threshold", type: .float, min: 0, max: 1, defaultValue: 0.6, step: 0.01)]),
            // Distortion
            spec("distort.bulge", "Bulge", "Distort", .coreImage, [f, gentle, ParamSpec(key: "x", name: "X", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.01), ParamSpec(key: "y", name: "Y", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.01)]),
            spec("distort.wave", "Ripple", "Distort", .coreImage, [f, ParamSpec(key: "frequency", name: "Frequency", type: .float, min: 0, max: 4, defaultValue: 1, step: 0.05)]),
            spec("distort.twist", "Twirl", "Distort", .coreImage, [f, gentle]),
            spec("distort.zoom", "Zoom Pulse", "Distort", .coreImage, [f, gentle]),
            spec("distort.smear", "Smear", "Distort", .metal, [f, ParamSpec(key: "angle", name: "Angle", type: .float, min: -180, max: 180, defaultValue: 45, step: 1)]),
            // Color processing
            spec("color.pixelate", "Pixelation", "Color", .coreImage, [f, ParamSpec(key: "size", name: "Size", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.02)]),
            spec("color.chromatic", "Chromatic Aberration", "Color", .metal, [f, gentle]),
            spec("color.invert", "Invert", "Color", .coreImage, [f]),
            spec("color.mono", "Monochrome", "Color", .coreImage, [f]),
            spec("color.mix", "Color Mix", "Color", .coreImage, [f, ParamSpec(key: "hue", name: "Hue", type: .float, min: 0, max: 1, defaultValue: 0.65, step: 0.01)]),
            // Film & texture
            spec("grain.film", "Film Grain", "Grain", .coreImage, [f, ParamSpec(key: "size", name: "Size", type: .float, min: 0, max: 1, defaultValue: 0.35, step: 0.02), ParamSpec(key: "mono", name: "Mono", type: .bool, min: 0, max: 1, defaultValue: 1, step: 1)]),
            spec("vignette.soft", "Vignette", "Vignette", .coreImage, [f, gentle]),
            spec("vignette.color", "Color Vignette", "Vignette", .coreImage, [f, ParamSpec(key: "color", name: "Color", type: .color, min: 0, max: 1, defaultValue: 0, step: 1)]),
            spec("grain.noise", "Noise", "Grain", .coreImage, [f, ParamSpec(key: "size", name: "Size", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.02)]),
            // Edge
            spec("edge.sharpen", "Sharpen", "Edge", .coreImage, [f, gentle]),
            spec("edge.highlights", "Edge Highlight", "Edge", .metal, [f]),
            spec("edge.xray", "X-Ray", "Edge", .metal, [f]),
            // Glitch
            spec("glitch.shift", "RGB Split", "Glitch", .metal, [f, ParamSpec(key: "shift", name: "Shift", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.02)]),
            spec("glitch.slices", "Slice Glitch", "Glitch", .metal, [f, ParamSpec(key: "count", name: "Slices", type: .int, min: 2, max: 24, defaultValue: 8, step: 1)]),
            spec("glitch.static", "Static", "Glitch", .metal, [f]),
            // Retro
            spec("retro.vhs", "VHS", "Retro", .metal, [f, ParamSpec(key: "tracking", name: "Tracking", type: .float, min: 0, max: 1, defaultValue: 0.4, step: 0.02)]),
            spec("retro.crt", "CRT", "Retro", .metal, [f, ParamSpec(key: "curve", name: "Curve", type: .float, min: 0, max: 1, defaultValue: 0.5, step: 0.02)]),
        ]
    }()

    public static func spec(_ id: String) -> EffectSpec? {
        catalogue.first { $0.id == id }
    }
}

// MARK: - Filter presets (color lookup + adjustments)

/// Color adjustment parameters (values in normalized -1..1 ranges where sensible).
public struct ColorAdjust: Hashable, Codable, Sendable {
    public var exposure: Float     // -2..2 EV
    public var brightness: Float   // -1..1
    public var contrast: Float     // -1..1
    public var highlights: Float   // -1..1
    public var shadows: Float      // -1..1
    public var saturation: Float   // -1..1 (0 = none, -1 = desaturate, 1 = push)
    public var vibrance: Float     // -1..1
    public var temperature: Float  // -1..1 (blue → amber)
    public var tint: Float         // -1..1 (green → magenta)
    public var fade: Float         // 0..1
    public var sharpen: Float      // 0..1
    public var vignette: Float     // 0..1
    public var grain: Float        // 0..1
    /// HSL shift chained curves: hueShift -0.5..0.5 (skip; replaced by curves where practical)
    public var hueShift: Float     // -0.5..0.5 full-cycle

    public init(exposure: Float = 0, brightness: Float = 0, contrast: Float = 0,
                highlights: Float = 0, shadows: Float = 0, saturation: Float = 0,
                vibrance: Float = 0, temperature: Float = 0, tint: Float = 0,
                fade: Float = 0, sharpen: Float = 0, vignette: Float = 0,
                grain: Float = 0, hueShift: Float = 0) {
        self.exposure = exposure
        self.brightness = brightness
        self.contrast = contrast
        self.highlights = highlights
        self.shadows = shadows
        self.saturation = saturation
        self.vibrance = vibrance
        self.temperature = temperature
        self.tint = tint
        self.fade = fade
        self.sharpen = sharpen
        self.vignette = vignette
        self.grain = grain
        self.hueShift = hueShift
    }

    public static let neutral = ColorAdjust()

    public func mixed(_ other: ColorAdjust, _ t: Float) -> ColorAdjust {
        func mix(_ a: Float, _ b: Float) -> Float { a + (b - a) * t }
        return ColorAdjust(
            exposure: mix(exposure, other.exposure),
            brightness: mix(brightness, other.brightness),
            contrast: mix(contrast, other.contrast),
            highlights: mix(highlights, other.highlights),
            shadows: mix(shadows, other.shadows),
            saturation: mix(saturation, other.saturation),
            vibrance: mix(vibrance, other.vibrance),
            temperature: mix(temperature, other.temperature),
            tint: mix(tint, other.tint),
            fade: mix(fade, other.fade),
            sharpen: mix(sharpen, other.sharpen),
            vignette: mix(vignette, other.vignette),
            grain: mix(grain, other.grain),
            hueShift: mix(hueShift, other.hueShift))
    }

    public var isNeutral: Bool { self == .neutral }
}

public struct FilterInstance: Hashable, Codable, Sendable {
    /// Preset id from FilterPreset.catalogue or "kino.custom".
    public var presetID: String
    public var adjustments: ColorAdjust

    public init(presetID: String = "kino.custom", adjustments: ColorAdjust = .neutral) {
        self.presetID = presetID
        self.adjustments = adjustments
    }
}

public enum FilterPreset {
    public struct Entry: Sendable {
        public let id: String
        public let name: String
        public let adj: ColorAdjust
        public init(_ id: String, _ name: String, _ adj: ColorAdjust) {
            self.id = "kino.\(id)"; self.name = name; self.adj = adj
        }
    }

    public static let catalogue: [Entry] = [
        Entry("original", "Original", ColorAdjust()),
        Entry("natura.lite", "Fresh", ColorAdjust(brightness: 0.02, contrast: 0.05, saturation: 0.06, vibrance: 0.08)),
        Entry("natura.warm", "Golden Hour", ColorAdjust(contrast: 0.03, saturation: 0.08, temperature: 0.16)),
        Entry("natura.cool", "Cool Air", ColorAdjust(brightness: 0.03, saturation: 0.04, temperature: -0.14)),
        Entry("video.vivid", "Vivid", ColorAdjust(contrast: 0.16, saturation: 0.30, vibrance: 0.22)),
        Entry("video.mov", "Classic Film", ColorAdjust(contrast: 0.08, saturation: -0.14, temperature: 0.05, fade: 0.12, grain: 0.18)),
        Entry("video.mono", "Noir", ColorAdjust(contrast: 0.24, saturation: -0.95, grain: 0.14)),
        Entry("video.fade", "Faded", ColorAdjust(brightness: 0.04, saturation: -0.20, fade: 0.30)),
        Entry("portrait.sweet", "Soft Glow", ColorAdjust(brightness: 0.05, contrast: -0.04, saturation: 0.05, grain: 0.05)),
        Entry("scene.sunset", "Sunset", ColorAdjust(contrast: 0.06, saturation: 0.18, temperature: 0.22, tint: 0.06)),
        Entry("scene.teal", "Cyan Teal", ColorAdjust(contrast: 0.12, highlights: 0.10, shadows: -0.06, saturation: -0.05, temperature: -0.10, tint: -0.08)),
    ]

    public static func preset(_ id: String) -> Entry? {
        catalogue.first { $0.id == id }
    }

    public static func name(for id: String) -> String {
        if id == "kino.custom" { return "Custom" }
        return catalogue.first(where: { $0.id == id })?.name ?? id
    }
}

// MARK: - Masks

public enum KMaskKind: String, Codable, CaseIterable, Sendable {
    case rectangle
    case circle
    case linear
    case split
    case freeform
    case custom // point-based polygon
}

public struct MaskSpec: Hashable, Codable, Sendable {
    public var id: UUID
    public var kind: KMaskKind
    /// Normalized center (0..1) in clip space.
    public var center: KVec2
    /// Normalized size (0..1 of clip bounds). For linear: distance from line to edge.
    public var size: KVec2
    public var rotation: Float
    public var feather: Float      // 0..1
    public var inverted: Bool
    /// For linear/split: line normal angle (degrees).
    public var lineAngle: Float
    /// For split: which side is visible (0/1).
    public var splitSide: Float
    /// freezeform polygon points (normalized, clip space). Empty when not used.
    public var points: [KVec2]

    public init(id: UUID = UUID(),
                kind: KMaskKind = .rectangle,
                center: KVec2 = KVec2(0.5, 0.5),
                size: KVec2 = KVec2(0.5, 0.5),
                rotation: Float = 0,
                feather: Float = 0.1,
                inverted: Bool = false,
                lineAngle: Float = 45,
                splitSide: Float = 0,
                points: [KVec2] = []) {
        self.id = id
        self.kind = kind
        self.center = center
        self.size = size
        self.rotation = rotation
        self.feather = feather
        self.inverted = inverted
        self.lineAngle = lineAngle
        self.splitSide = splitSide
        self.points = points
    }
}

// MARK: - Chroma key instance

/// RGB triplet used by chroma keying (Codable-safe, no tuples).
public struct KRGB: Hashable, Codable, Sendable {
    public var r: Float
    public var g: Float
    public var b: Float
    public init(r: Float, g: Float, b: Float) { self.r = r; self.g = g; self.b = b }
    public var colorHex: UInt32 {
        (UInt32(min(1, r) * 255) << 16) | (UInt32(min(1, g) * 255) << 8) | UInt32(min(1, b) * 255)
    }
    /// Normalized proximity vs another color (0..1).
    public func distance(to o: KRGB) -> Float {
        let dr = r - o.r, dg = g - o.g, db = b - o.b
        return min(1, sqrt(dr * dr + dg * dg + db * db) / 1.7320508)
    }
}

public struct ChromaKeySpec: Hashable, Codable, Sendable {
    public var keyColor: KRGB
    public var similarity: Float   // tolerance 0..1
    public var smoothness: Float   // edge cleanup 0..1
    public var spill: Float        // spill suppression 0..1
    public var edgeFeather: Float

    public init(keyColor: KRGB = KRGB(r: 0, g: 1, b: 0),
                similarity: Float = 0.2, smoothness: Float = 0.2,
                spill: Float = 0.3, edgeFeather: Float = 0.05) {
        self.keyColor = keyColor
        self.similarity = similarity
        self.smoothness = smoothness
        self.spill = spill
        self.edgeFeather = edgeFeather
    }

    public init(colorHex: UInt32, similarity: Float = 0.2, smoothness: Float = 0.2, spill: Float = 0.3, edgeFeather: Float = 0.05) {
        self.init(keyColor: KRGB(r: Float((colorHex >> 16) & 0xFF) / 255,
                                 g: Float((colorHex >> 8) & 0xFF) / 255,
                                 b: Float(colorHex & 0xFF) / 255),
                  similarity: similarity, smoothness: smoothness, spill: spill, edgeFeather: edgeFeather)
    }

    public static let `default` = ChromaKeySpec()
}
